### ISSUE TITLE
Compatibility Ars Magica 2

### ISSUE THREAD

**Issue by ewokz750** [MinecraftPortCentral/Cauldron-Issues#10] opened 2014-10-10 10:07 UTC
We're currently running a SMP server with both AM2 and Cauldron and we've noticed a fairly serious bug. When players try to create spells in ars magica 2 the process is for the most part skipped, leaving players with a bugged out spell and no way to create a functioning one. This effectively breaks the mod.

We've tried the mod without Cauldron and it runs properly, as well as in SP. Obviously there's something occurring during the spell creation process but I couldn't explain what. Apparently the issues been present since the later stages of MCPC+ for 1.6 and has continued until now, there's a bug thread that was opened with AM2 but it was closed after they worked out it was caused by MCPC/Cauldron. 

link: https://github.com/Mithion/ArsMagica2/issues/533

That might shed more light on the bug as the guy seems to understand it more than me.

**Comment by McyD** [comment] 2014-10-17 20:20
I can confirm this, I have the same issue on my server.  Spells work fine in SSP, and when running a non-cauldron server.

**Comment by BourgeoisArab** [comment] 2014-10-21 16:15
I have this too. Any ideas as to what is causing this bug?

**Comment by LargePrime** [comment] 2014-10-21 18:21
https://github.com/Mithion/ArsMagica2/issues/865
This is the Ender boots illegal stance bug

I do not know if this should be split into a different issue or added to the general Ars Magica incompatibility.
I leave it to you

**Comment by bloodmc** [comment] 2014-10-22 21:28
What version of Cauldron are you using?

**Comment by BourgeoisArab** [comment] 2014-10-23 15:56
I'm using Cauldron 1.7.10-1.1231.01.206; haven't got around to updating to 207 yet.

**Comment by tgarr0** [comment] 2014-10-23 16:20
Just tested with Cauldron 1.7.10-1231.01.207; it's still an issue in this version.

**Comment by jermangarc** [comment] 2014-10-25 06:20
Same here as the rest. Running Cauldron 1.7.10-1231.01.207.

**Comment by bloodmc** [comment] 2014-10-26 03:12
Create a test world with everything setup to reproduce the bug then explain exactly how to replicate it. Make sure to ONLY use Ars Magica 2 and Cauldron.

**Comment by bloodmc** [comment] 2014-10-26 05:37
Once I fix this issue, I will release the next update so get me that test world =)

**Comment by tgarr0** [comment] 2014-10-26 05:39
I've isolated the source of the problem.  In this most recent version of Ars Magica, the Inscription Table outputs an unsigned Book & Quill with spell creation information, and more importantly hidden NBT information for the Crafting Altar to use.  The Lectern, however, only accepts signed books.  In signing these books on a Cauldron server, the additional NBT data (within its "tag" tag) needed by the Altar is stripped away or ignored (leading to 'empty' spells).  I spliced the "tag" data from an unsigned book into a signed one to verify, and it functioned as it should have within the Crafting Altar.

**Comment by tgarr0** [comment] 2014-10-26 05:54
This is the testworld I used: http://www.filedropper.com/arsmagicatestworld

**Comment by bloodmc** [comment] 2014-10-26 07:42
@tgarr0 you still need to provide exact steps on how to replicate issue as I do not play this mod. It would also help if you uploaded a player file with the exact inventory required to make bug happen so I can clone it to my player. Also if you can, provide a working player dat file where everything works as expected so I can compare NBT to see what exactly is missing.

**Comment by LargePrime** [comment] 2014-10-26 14:02
blood;  the link provided has technical info as to why cauldron is behaving different than forge.
is that sufficient?  if not what more do you need.
thanks for your work

**Comment by bloodmc** [comment] 2014-10-26 16:07
@LargePrime Mithion/ArsMagica2#865 has been fixed and will be included in next update.

**Comment by LargePrime** [comment] 2014-10-26 16:29
i thank you sir

**Comment by tgarr0** [comment] 2014-10-26 16:32
Re-upload of testworld with inventory and properly-working NBT-spliced Written Book: http://www.filedropper.com/am2testworldv2
This mod is a bit harder to explain than most, so I'll try to keep it to the bare minimum needed for testing.  This will assume either Creative Mode or use of my player data to avoid explaining how to get spell components.
Making the Spell Recipe:
Interact with the Inscription Table.  Place a Book & Quill into the slot in its interface.  Drag a square spell component (like Projectile) into one of the large squares near the bottom of the interface.  Drag 
an octagonal component (like Magic Damage or Heal) into the bar at the bottom of the interface.  Remove the Book & Quill from the interface.  It now contains information for the spell's creation, including extra data outside of page contents.
Making the Spell:
The Book & Quill must be finalized (signed) before it can be used; the title given won't matter.  This is when the extra data is lost.  The large quartz multiblock structure is the Crafting Altar; place the signed book onto the Lectern (wooden pedestal) via right-click.  (Shift+right-click with an empty hand to remove it later.)  To start this (or any) spell crafting process, throw a Blank Rune into the center of the altar.  Subsequent items to be tossed into the altar's center will be shown above the Lectern; in this case, it will just be the spell-ending Spell Parchment (which may also be used to prematurely end a normal spell creation process).  A useless spell will be produced.  To see what is intended to happen, use the "NBT Spliced" book on the altar.

**Comment by bloodmc** [comment] 2014-10-26 20:24
@tgarr0 @ewokz750 @LargePrime @jakoubeck503 @jermangarc Bug has been fixed and will be included in next update. It was caused by CraftBukkit's PlayerEditBookEvent handle logic which would create a new NBTTagCompound instead of using the existing one.

**Comment by jermangarc** [comment] 2014-10-26 20:27
@bloodmc and @tgarr0 Dudes! You are a scholars and a gentlemen! I don't play AM myself but the guys in my private clan server do, all I do is admin the server. I knew the spells weren't working but didn't know how or why. The clan is going to be stoked! Thanks a million! cap-minecraft.net

**Comment by bloodmc** [comment] 2014-10-26 21:03
Fixed in build 208. Make sure you wipe out your libraries folder before installing new version. This fix is included in the new API build.

**Closed as completed by bloodmc** 2014-10-26 21:03 UTC

**Comment by JamieStar** [comment] 2015-03-14 23:36
Hey I cant even run my server with Ars Magica on there
