### ISSUE TITLE
Client crash when switching server w/ bungeecord

### ISSUE THREAD

**Issue by Hatventures** [MinecraftPortCentral/Cauldron-Issues#114] opened 2014-11-29 16:48 UTC
Hey.

We've been using (extensivly) Cauldron with Bungeecord on 1.6.4. It worked flawlessly.

We'are about to move onto 1.7.10, and we're having issues when switching servers.

When a client switches server, it crashes. But the weird part are the crash reasons. Here are a few:

http://pastebin.com/HfmQ3Rk4
http://pastebin.com/jvy7ZHFL
http://pastebin.com/r0wY9W5Y
http://pastebin.com/fm8MfW3j

I've tried many manipulations (such as empty maps, or mirroring a server to make sure everything is "compatible") but alas, no success.

I'm not 100% sure this is a cauldron issue (it could be as easily a bungeecord one), but you may have an idea about what's causing the issue.

I tried to remove some mods and such, but being a large modpack, it would take some time to test mods one by one (which i'll do if you have no idea what's causing this).

If you require any more data, or any specific manipulations, i'll be happy to oblige.

**Server details**
Minecraft: 1.7.10
Cauldron: 1236.05.212 (latest)
BungeeCord: 1021 (latest)

Thanks a bunch, and keep up the good work.

dimensionZ

**Comment by ghost** [comment] 2014-11-29 19:23
I've been having identical issues with the same builds, I don't think it occurred before some of the latest patches (can't say for certain, might've just been lucky), so it could be a Cauldron issue, although I'd assume it's something to do with the handshake reset process. I have 2 servers that work currently, but adding and trying to switch to a 3rd with the same mods and a fresh map caused crashes again.

I can do some testing with dev builds etc if need be, the server isn't live yet.

**Comment by johnfriedrich** [comment] 2014-11-30 03:42
Did you try joining directly these servers by bypassing bungeecord by using the raw ip+port?
Same crashes?

Could you provide the loglines when a player tries to switch servers? Both cauldron and Bungee log
I think it's not necessary to ask, but just to make sure: Latest Client Forge installed?

**Comment by Hatventures** [comment] 2014-11-30 03:46
It only happens when switching server. Connecting is fine, and as long as you dont switch, no issie.

I will provide the logs later today, but they didnt contain anything soecial.

As for forge, tried both latest and recommanded

**Comment by johnfriedrich** [comment] 2014-11-30 03:51
Probably try to run cauldron without any mods but with your map.
Because I don't think it's not a BungeeCord/cauldron) issue.

**Comment by bloodmc** [comment] 2014-11-30 08:42
@Hatventures Please test the build below

https://www.dropbox.com/s/z7pwieaudaft5fu/BungeeCord-Cauldron-B1.jar?dl=0

**Comment by Hatventures** [comment] 2014-11-30 09:32
Thank you for this build but i'm afraid we still crash :( Hopefully a step in the right direction!

http://pastebin.com/gec0x4HZ

**Comment by bloodmc** [comment] 2014-11-30 09:56
@Hatventures Try again, I fixed a bug in my PR but still not sure if it is related to this issue.

**Comment by Hatventures** [comment] 2014-11-30 10:29
@bloodmc same exact crash i'm afraid

http://pastebin.com/JVds5bhG

Is there any way i can output more logs for you?

**Comment by bloodmc** [comment] 2014-11-30 10:31
@Hatventures You need to figure out what mod is causing it so I can reproduce it on my end.

**Comment by Hatventures** [comment] 2014-11-30 10:37
@bloodmc
Alright we'll start checking mod by mod. Thanks

**Comment by bloodmc** [comment] 2014-11-30 10:39
@Hatventures Start by removing everything related to openmods as that had issues in the past.

**Comment by Hatventures** [comment] 2014-11-30 10:40
@bloodmc yeah, their idsync was on my crosshair

**Comment by bloodmc** [comment] 2014-11-30 10:44
@Hatventures Also please include your Bungee log which is labeled as "proxy.log.0".

**Comment by Hatventures** [comment] 2014-11-30 10:45
@bloodmc not much was in the logs, player simply crashed after idsync line

**Comment by bloodmc** [comment] 2014-11-30 10:47
@Hatventures Doesn't matter how little, I will need that log as well.

**Comment by Hatventures** [comment] 2014-11-30 21:05
@bloodmc Finally figured out which mod is the issue. And the winner is ...

**Immibis Core 59.0.4**

Bungeecord Logs 

> 21:55:21 [INFO] [dimensionZ75] <-> ServerConnector [test1] has connected
> 21:55:36 [INFO] [dimensionZ75] <-> ServerConnector [test3] has connected
> 21:55:37 [INFO] [dimensionZ75] <-> DownstreamBridge <-> [test1] has disconnected
> 21:55:45 [WARNING] [dimensionZ75] -> UpstreamBridge - IOException: Connection reset by peer
> 21:55:45 [INFO] [dimensionZ75] disconnected with: IOException : Connection reset by peer @ > sun.nio.ch.FileDispatcherImpl:-2
> 21:55:45 [INFO] [dimensionZ75] -> UpstreamBridge has disconnected
> 21:55:45 [INFO] [dimensionZ75] disconnected with: [Proxy] Lost connection to server.
> 21:55:45 [INFO] [dimensionZ75] <-> DownstreamBridge <-> [test3] has disconnected

Without that mod (and dimensional anchors, which uses immibis), there's no issue (~149 mods).

If you require any other information, i'd be happy to help.

**Comment by bloodmc** [comment] 2014-11-30 21:20
@Hatventures Immibis needs to add support for FML's reset handshake process as clients can switch servers in BungeeCord , without disconnecting, causing FML to fire another connection event. Currently, immibis core mod listens for FML's connection events and adds handlers to the pipeline as seen here

```
@SubscribeEvent
public void onClientConnection(FMLNetworkEvent.ClientConnectedToServerEvent evt) {
    ChannelPipeline pipeline = evt.manager.channel().pipeline();
    pipeline.addBefore("fml:packet_handler", "immibis core mod packet handler", this);
    pipeline.addLast("immibis core special packet handler", new FakeSpecialPacketHandler());
    pipeline.addFirst("immibis core packet capture", new PacketCaptureHandler());
}

@SubscribeEvent
public void onServerConnection(FMLNetworkEvent.ServerConnectionFromClientEvent evt) {
    ChannelPipeline pipeline = evt.manager.channel().pipeline();
    pipeline.addBefore("fml:packet_handler", "immibis core mod packet handler", this);
    pipeline.addLast("immibis core special packet handler", new FakeSpecialPacketHandler());
    pipeline.addFirst("immibis core packet capture", new PacketCaptureHandler());
}
```

A check needs to be added to see if the handler already exists to avoid the crash.

@immibis can this be fixed on your end?

**Comment by bloodmc** [comment] 2014-12-01 04:24
@Hatventures @Nentify Fixed in Immibis Core 59.0.5

http://immibis.com/mcmoddl/files/immibis-core-59.0.5.jar

**Closed as completed by bloodmc** 2014-12-01 04:24 UTC

**Comment by Hatventures** [comment] 2014-12-01 13:31
@bloodmc I'm sorry to re-open, but it seems the issues are back. (Immibis caused the multiplayer class error, but not the cast, at least it wasnt the only one causing it)

I tried to add one mod at a time, and found that with pneumaticcraft, i would crash, and without i wouldnt. But then, later on i started to crash again, even without pneumatic craft.

Is there anyway I can output more logs? 
Is there anything else I can do?
Since crashes arent happening 100% of the time, it makes A/B testing near impossible, and i'm frankly not far from giving up.

Here are some crash reports:
http://pastebin.com/U77cMNCD
http://pastebin.com/eT3KfmRs
http://pastebin.com/4kbhDmyC

**Comment by Hatventures** [comment] 2014-12-01 13:48
@bloodmc Since that particular crash isnt mod related, it might give you a bigger clue:
http://pastebin.com/Jq6q6V1e

**Comment by bloodmc** [comment] 2014-12-01 14:09
@Hatventures Disable Railcraft's TileHidden in config to fix the cast problems.

**Comment by Hatventures** [comment] 2014-12-01 14:16
@bloodmc In railcraft.cfg

> I:block.hidden=0

Which, if i'm not mistaken, means that it's already disabled, isnt it?

**Comment by bloodmc** [comment] 2014-12-01 14:18
@Hatventures Yes, I'll see if I can track down the render problem later.

**Comment by Hatventures** [comment] 2014-12-01 14:38
@bloodmc thank you. I'll keep trying to make sense of it all. But i'm not sure i fully understand what is going on.

**Comment by Hatventures** [comment] 2014-12-02 12:06
@bloodmc I've done some more tests, and maybe this is just a coincidence and/or nonsense. But i've been recording pluginMessages (via a bungee plugin) to know what's going on when a user change server.

**Crashes**
http://pastebin.com/0mC5jPmt
http://pastebin.com/3cyJ88nj

**OK**
http://pastebin.com/yB3N8U5q
http://pastebin.com/F8Dg6zfu
http://pastebin.com/fNZEaJ7A
(there's more, but reached pastebin limits, and they are all about the same)

What i notice is the following, when no crash happens:

```
12:38:57 [FINE] [DONE Server <- Bungee][RECEIVED: HandshakeAck]
12:38:57 [INFO] [HatLink] witchery = net.md_5.bungee.ServerConnection@416f96f9 -> dimensionZ75 (37)
12:38:57 [FINE] [COMPLETE Client -> Bungee][SENDING: HandshakeAck]
12:38:57 [FINE] [DONE Server <- Bungee][RECEIVED: HandshakeAck]
```

The 2 Handshake acks are Done close appart, and no mods plugin message are between them

But when there's a crash, there's a lot more between the two:

```
12:29:35 [FINE] [DONE Server <- Bungee][RECEIVED: HandshakeAck]
12:29:35 [INFO] [HatLink] CoFH = net.md_5.bungee.ServerConnection@7195de9a -> dimensionZ75 (2)
12:29:35 [INFO] [HatLink] CoFH = net.md_5.bungee.ServerConnection@7195de9a -> dimensionZ75 (21)
12:29:35 [INFO] [HatLink] baubles = net.md_5.bungee.ServerConnection@7195de9a -> dimensionZ75 (8)
12:29:35 [INFO] [HatLink] baubles = net.md_5.bungee.ServerConnection@7195de9a -> dimensionZ75 (8)
12:29:35 [INFO] [HatLink] baubles = net.md_5.bungee.ServerConnection@7195de9a -> dimensionZ75 (8)
12:29:35 [INFO] [HatLink] baubles = net.md_5.bungee.ServerConnection@7195de9a -> dimensionZ75 (8)
12:29:35 [INFO] [HatLink] thaumcraft = net.md_5.bungee.ServerConnection@7195de9a -> dimensionZ75 (1)
12:29:35 [INFO] [HatLink] thaumcraft = net.md_5.bungee.ServerConnection@7195de9a -> dimensionZ75 (434)
12:29:35 [INFO] [HatLink] thaumcraft = net.md_5.bungee.ServerConnection@7195de9a -> dimensionZ75 (3)
12:29:35 [INFO] [HatLink] thaumcraft = net.md_5.bungee.ServerConnection@7195de9a -> dimensionZ75 (3)
12:29:35 [INFO] [HatLink] thaumcraft = net.md_5.bungee.ServerConnection@7195de9a -> dimensionZ75 (3)
12:29:35 [INFO] [HatLink] thaumcraft = net.md_5.bungee.ServerConnection@7195de9a -> dimensionZ75 (50)
12:29:35 [INFO] [HatLink] thaumcraft = net.md_5.bungee.ServerConnection@7195de9a -> dimensionZ75 (6)
12:29:35 [INFO] [HatLink] thaumcraft = net.md_5.bungee.ServerConnection@7195de9a -> dimensionZ75 (6)
12:29:35 [INFO] [HatLink] thaumcraft = net.md_5.bungee.ServerConnection@7195de9a -> dimensionZ75 (6)
12:29:35 [INFO] [HatLink] thaumcraft = net.md_5.bungee.ServerConnection@7195de9a -> dimensionZ75 (15)
12:29:35 [INFO] [HatLink] enderio = net.md_5.bungee.ServerConnection@7195de9a -> dimensionZ75 (19)
12:29:35 [INFO] [HatLink] enderio = net.md_5.bungee.ServerConnection@7195de9a -> dimensionZ75 (6)
12:29:35 [INFO] [HatLink] enderio = net.md_5.bungee.ServerConnection@7195de9a -> dimensionZ75 (39)
12:29:35 [INFO] [HatLink] enderio = net.md_5.bungee.ServerConnection@7195de9a -> dimensionZ75 (26)
12:29:35 [INFO] [HatLink] XU|Pkt = net.md_5.bungee.ServerConnection@7195de9a -> dimensionZ75 (16)
12:29:35 [INFO] [HatLink] GalacticraftCore = net.md_5.bungee.ServerConnection@7195de9a -> dimensionZ75 (5)
12:29:35 [INFO] [HatLink] hee = net.md_5.bungee.ServerConnection@7195de9a -> dimensionZ75 (254)
12:29:35 [INFO] [HatLink] iChunUtil = net.md_5.bungee.ServerConnection@7195de9a -> dimensionZ75 (92)
12:29:35 [INFO] [HatLink] iChunUtil = net.md_5.bungee.ServerConnection@7195de9a -> dimensionZ75 (13)
12:29:35 [INFO] [HatLink] IC2NC = net.md_5.bungee.ServerConnection@7195de9a -> dimensionZ75 (20)
12:29:35 [INFO] [HatLink] MineTweaker3 = net.md_5.bungee.ServerConnection@7195de9a -> dimensionZ75 (1236)
12:29:35 [INFO] [HatLink] Morph = net.md_5.bungee.ServerConnection@7195de9a -> dimensionZ75 (26)
12:29:35 [INFO] [HatLink] Morph = net.md_5.bungee.ServerConnection@7195de9a -> dimensionZ75 (235)
12:29:35 [INFO] [HatLink] SimplyJetpacks = net.md_5.bungee.ServerConnection@7195de9a -> dimensionZ75 (498)
12:29:35 [INFO] [HatLink] WRCBE = net.md_5.bungee.ServerConnection@7195de9a -> dimensionZ75 (3)
12:29:35 [INFO] [HatLink] WRCBE = net.md_5.bungee.ServerConnection@7195de9a -> dimensionZ75 (4)
12:29:35 [INFO] [HatLink] WRCBE = net.md_5.bungee.ServerConnection@7195de9a -> dimensionZ75 (6)
12:29:35 [INFO] [HatLink] WRCBE = net.md_5.bungee.ServerConnection@7195de9a -> dimensionZ75 (6)
12:29:35 [INFO] [HatLink] ThaumicTinkerer|B = net.md_5.bungee.ServerConnection@7195de9a -> dimensionZ75 (2)
12:29:35 [INFO] [HatLink] GalacticraftCore = net.md_5.bungee.ServerConnection@7195de9a -> dimensionZ75 (9)
12:29:35 [INFO] [HatLink] Hats = net.md_5.bungee.ServerConnection@7195de9a -> dimensionZ75 (22)
12:29:35 [INFO] [HatLink] Hats = net.md_5.bungee.ServerConnection@7195de9a -> dimensionZ75 (42)
12:29:35 [INFO] [HatLink] LogisticsPipes = net.md_5.bungee.ServerConnection@7195de9a -> dimensionZ75 (38)
12:29:35 [INFO] [HatLink] LogisticsPipes = net.md_5.bungee.ServerConnection@7195de9a -> dimensionZ75 (42)
12:29:35 [INFO] [HatLink] MEK = net.md_5.bungee.ServerConnection@7195de9a -> dimensionZ75 (317)
12:29:35 [INFO] [HatLink] MEK = net.md_5.bungee.ServerConnection@7195de9a -> dimensionZ75 (85)
12:29:35 [INFO] [HatLink] MEK = net.md_5.bungee.ServerConnection@7195de9a -> dimensionZ75 (9)
12:29:35 [INFO] [HatLink] MEK = net.md_5.bungee.ServerConnection@7195de9a -> dimensionZ75 (9)
12:29:35 [INFO] [HatLink] MobAmputation = net.md_5.bungee.ServerConnection@7195de9a -> dimensionZ75 (14)
12:29:35 [INFO] [HatLink] BC-CORE = net.md_5.bungee.ServerConnection@7195de9a -> dimensionZ75 (171)
12:29:35 [FINE] [COMPLETE Client -> Bungee][SENDING: HandshakeAck]
12:29:35 [FINE] [DONE Server <- Bungee][RECEIVED: HandshakeAck]
```

Now, i do not think that's the root of the issue, but if i beleive what i'm seeing, there's a relationship with crashes and when the handshake is done, maybe the fact that some data is sent before the handshake is complete means that there's a mix of data which causes the crash.

Again ... could mean nothing, but i'd rather tell you my findings.

dimensionZ

**Comment by ghost** [comment] 2015-01-11 17:29
Any updates on this issue, or should we try to find some sort of solution ourselves?
