### ISSUE TITLE
Terrafirmacraft mobs do not drop items on death

### ISSUE THREAD

**Issue by Obatunde** [MinecraftPortCentral/Cauldron-Issues#30] opened 2014-10-20 22:06 UTC
using Cauldron CauldronInstallerPatch-1.1231.01.207
and Terrafirmacraft [1.7.10]TerraFirmaCraft-0.79.8.328
animals do not drop meat or leather, they just disapear upon death.

**Comment by Azaysol** [comment] 2014-10-21 17:06
this is running java 7update 67 also tried with 71, on windows and linux machines.
there are no error logs to report because the server does not crash or see any issues.
in cauldron 1.6.4 and tfc 1.6.4 this used to work fine

**Comment by Brycey92** [comment] 2014-10-21 17:14
Aldo also tested in normal forge, where the issue was not present.

**Comment by bloodmc** [comment] 2014-10-26 04:46
Caused by same bug as https://github.com/MinecraftPortCentral/Cauldron-Issues/issues/15

Fixed in next update which will be released soon.

**Comment by bloodmc** [comment] 2014-10-26 21:04
Fixed in build 208.

**Closed as completed by bloodmc** 2014-10-26 21:04 UTC
