### ISSUE TITLE
Crash in 1.1231.04.209

### ISSUE THREAD

**Issue by Xfel** [MinecraftPortCentral/Cauldron-Issues#74] opened 2014-11-09 14:45 UTC
https://gist.github.com/Xfel/4219aa06b73767afb5fd

It seems that no mods are involved. The only thing that could cause this (in my opinion) is a null entry in the Block.blockList array, but as the crash report itself correctly identifies a block type, this cannot be the case. Is it possible that there is a cauldron patch in that area? (This is a best guess based on the vanilla code in that method and the fact that MinecraftForge doesn't have a patch for this part)

**Comment by Dav92** [comment] 2014-11-09 16:48
I also get that crash once in a while since updating ~20 mods in the last day. It only happens with Cauldron, with a normal Forge server I could play without problems for hours. The problem with this crash is, that I can't really reproduce it. Sometimes I can play an hour, sometimes only a couple of seconds/minutes.

**Comment by aallen42** [comment] 2014-11-09 17:10
I also get this crash after updating our own mod pack - if you cross reference our updated mod list with BTP 10.8, you get the following mods as likely culprits:

Botania r1.3-134.jar
buildcraft-6.1.7.jar
CoFHCore-[1.7.10]3.0.0B8-36.jar
CoFHLib-[1.7.10]1.0.0B7-29.jar
EnderIO-1.7.10-2.1.8.269.jar
MineFactoryReloaded-[1.7.10]2.8.0RC4-676.jar
OpenBlocks-1.7.10-1.3-snapshot-475.jar
OpenModsLib-1.7.10-0.6-snapshot-246.jar
RedstoneArsenal-[1.7.10]1.1.0RC1-19.jar
ThermalExpansion-[1.7.10]4.0.0B6-16.jar

I will be doing some more testing later to attempt to identify which one it is...

**Comment by aallen42** [comment] 2014-11-09 17:39
We have been doing some troubleshooting and it appears that this issue is caused by the Openblocks fan pushing entities.

EDIT: It seems the culprit is actually MFR grinders...

**Comment by Dav92** [comment] 2014-11-09 18:22
I don't use the OpenBlocks fans so far, so it's not necessarilly that. Out of the mods you listed, I updated the following:
buildcraft-6.1.7.jar
CoFHCore-[1.7.10]3.0.0B8-36.jar
CoFHLib-[1.7.10]1.0.0B7-29.jar
MineFactoryReloaded-[1.7.10]2.8.0RC4-676.jar
OpenBlocks-1.7.10-1.3-snapshot-475.jar
OpenModsLib-1.7.10-0.6-snapshot-246.jar
RedstoneArsenal-[1.7.10]1.1.0RC1-19.jar
ThermalExpansion-[1.7.10]4.0.0B6-16.jar

I already tried it with an older version of Buildcraft where that crash never happened, and after a a while it also happened. So I think we can take Buildcraft out of the list of mods that could be causing this.

**Comment by aallen42** [comment] 2014-11-09 18:43
If it's not openblocks it's almost certainly a CoFH mod (inc. MFR)

**Comment by Dav92** [comment] 2014-11-09 18:50
I'll revert to the last working versions of all the CoFH mods and try it there. I'll report back tomorrow if it crashed again, or not.

**Comment by Dav92** [comment] 2014-11-09 19:01
Seems someone's having the same issue with just MFR RC4:
https://github.com/skyboy/MineFactoryReloaded/issues/296

**Comment by aallen42** [comment] 2014-11-09 20:10
Yes, that makes sense. I'll see if I can eliminate the problem by removing all grinders.

**Comment by jznomoney** [comment] 2014-11-09 21:17
Happens to me to when I enabled my grinders server crashed had to use vanilla forge to get it back up.

**Comment by Xfel** [comment] 2014-11-10 10:52
Even though the cause of it might actually be MFR, Cauldron is likely part of the cause too, as it does apparently work when using a normal forge server.

**Comment by bloodmc** [comment] 2014-11-11 21:38
I'll fix this over the weekend when I get some time. I already found the cause =)

**Comment by Slind14** [comment] 2014-11-12 08:32
@bloodmc might sharing what you found out?

**Comment by bloodmc** [comment] 2014-11-16 21:10
Fixed in build 210

**Closed as completed by bloodmc** 2014-11-16 21:10 UTC
