### ISSUE TITLE
COFHCore V3.0.0B7-35 server crash

### ISSUE THREAD

**Issue by tekman123** [MinecraftPortCentral/Cauldron-Issues#65] opened 2014-11-07 03:55 UTC
I'm running a server with the above mentioned version of COFHCore and it won't even let my server start up Crashlog: http://paste.ubuntu.com/8860792/.  Tried reporting to cofh via #thermalexpansion and Skyboy says this "[09:43.16] <+skyboy> but since they're still not allowed to distribute anything, and there are no sources available, i'm not supporting it".  So I thought I would report here since I am Running the server with Cauldron for forge 1231

**Comment by jznomoney** [comment] 2014-11-07 14:56
I think I may have the same issue but I can't even get to the point you did with the server.  Here is the brief log I get pastebin.com/MDGDzqZR

**Comment by aallen42** [comment] 2014-11-07 21:25
Same issue: http://pastebin.com/yfZPsMN1

**Comment by Redlotus99** [comment] 2014-11-08 16:10
Similar issue here.

**Comment by Dav92** [comment] 2014-11-08 16:26
The crash got fixed with COFHCore V3.0.0B8-36. At least the crash @tekman123 and @tubbytoad42 reported.

**Comment by Redlotus99** [comment] 2014-11-09 06:05
Still crashing on startup.

http://pastebin.com/8L5gJ0Vt

**Comment by bloodmc** [comment] 2014-11-11 21:32
[java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: java.lang.RuntimeException: asm error net.minecraft.entity.Entity %cb:JbbV7ab5=Cc(<_b#=aPWc[/cHbc%+EPEW]DX,S[ dr /3cVUFbHF7cQ68C>?cc<8ac<WWO6)]D6M`b+2cb4A_` 0 1

Looks like they are injecting some ASM into the Entity class which fails in Cauldron since it is different than Forge's. I'll contact skyboy to see if I can assist with a fix.

Before I do, @tekman123 please confirm the issue still exists.

**Comment by Redlotus99** [comment] 2014-11-11 22:17
As far as I can tell for me I have it fixed. I had fastcraft installed also and apparently for whatever reason it's not compatible with Cauldron.

Sent from my T-Mobile 4G LTE Device

<div>-------- Original message --------</div><div>From: bloodmc <notifications@github.com> </div><div>Date:11/11/2014  3:32 PM  (GMT-06:00) </div><div>To: MinecraftPortCentral/Cauldron-Issues <Cauldron-Issues@noreply.github.com> </div><div>Cc: Redlotus99 <dg25@hotmail.com> </div><div>Subject: Re: [Cauldron-Issues] COFHCore V3.0.0B7-35 server crash (#65) </div><div>
</div>

[java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: java.lang.RuntimeException: asm error net.minecraft.entity.Entity %cb:JbbV7ab5=Cc(<_b#=aPWc[/cHbc%+EPEW]DX,S[ dr /3cVUFbHF7cQ68C>?cc<8ac<WWO6)]D6M`b+2cb4A_` 0 1

Looks like they are injecting some ASM into the Entity class which fails in Cauldron since it is different than Forge's. I'll contact skyboy to see if I can assist with a fix.

Before I do, @tekman123 please confirm the issue still exists.

---

**Comment by bloodmc** [comment] 2014-11-16 08:40
OK Thanks.

**Closed as completed by bloodmc** 2014-11-16 08:40 UTC

**Comment by morlanius** [comment] 2014-11-28 16:20
issue still occurring on latest version of cauldron and CoFHcore version B8-36

**Comment by Thornbush42** [comment] 2015-02-21 16:29
I can confirm this crash is still happening, even with the latest CoFH Core version: http://pastebin.com/zccwR7dp
